"""Fixed evaluator; output quality failures are findings, not test failures.

v2 (2026-09-17, after audit): gate decisions are recomputed from the cached model outputs
with the current rag.verify (the v1 gate was case-sensitive while this scorer lowercases);
an always-refuse trivial baseline is reported; per-slice recall, citation precision
(book ch. 38) and an LLM-entailment gate (book ch. 46, entail.py) are added; the EM gap
carries a McNemar exact p and Wilson intervals. Model outputs in predictions.jsonl are
never regenerated by this script; delete the file for a fresh run."""
import collections, hashlib, json, math, platform, re, string, time
from pathlib import Path
import numpy as np
from rag import run, verify
from entail import claim_supports
ROOT = Path(__file__).parent
def normalize(s):
    s = ''.join(c for c in s.lower() if c not in string.punctuation)
    return ' '.join(re.sub(r'\b(a|an|the)\b', ' ', s).split())
def f1(pred, gold):
    a, b = normalize(pred).split(), normalize(gold).split()
    if not a or not b:
        return float(a == b)
    common = sum((collections.Counter(a) & collections.Counter(b)).values())
    return 2 * common / (len(a) + len(b))
def wilson(k, n, z=1.96):
    p = k / n; d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d; h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return [round(c - h, 3), round(c + h, 3)]
def mcnemar_exact(b, c):
    n = b + c
    if n == 0:
        return 1.0
    tail = sum(math.comb(n, k) for k in range(0, min(b, c) + 1)) / 2 ** n
    return min(1.0, 2 * tail)
def unit_checks():
    assert verify('42', 'The answer is 42.', ['The answer is 42.'])
    assert verify('Answer', 'the answer is here', ['The Answer is here'])  # case-folded (v2 fix)
    assert not verify('43', 'The answer is 42.', ['The answer is 42.'])
    assert not verify('42', 'Invented 42.', ['The answer is 42.'])
    assert not verify('', '', ['Anything'])
    assert not verify(None, '42', ['42'])
    assert not verify('42', '42', [])
    assert f1('The red car', 'red car') == 1 and f1('', '') == 1
    assert f1('red', 'blue') == 0
    assert mcnemar_exact(0, 0) == 1.0 and abs(mcnemar_exact(2, 1) - 1.0) < 1e-9 and mcnemar_exact(10, 0) < 0.01
    for q, c in [('', 'x'), ('x', ''), (None, 'x')]:
        try:
            run(q, c)
        except ValueError:
            continue
        raise AssertionError('Invalid input accepted')
unit_checks()
cases = json.loads((ROOT / 'data/evaluation.json').read_text())
assert len(set(c['id'] for c in cases)) == len(cases)
for c in cases:
    assert all(a in c['context'] for a in c['answers'])
out = ROOT / 'results/predictions.jsonl'
records = []
if out.exists():
    records = [json.loads(line) for line in out.read_text().splitlines()]
seen = {r['id'] for r in records}
for i, c in enumerate(cases):
    if c['id'] in seen:
        continue
    start = time.perf_counter()
    result = run(c['question'], c['context'])
    row = {**c, **result, 'seconds': time.perf_counter() - start}
    with out.open('a', encoding='utf-8') as handle:
        handle.write(json.dumps(row) + '\n')
    records.append(row)
    print(f"{i+1:02d}/24 | {c['topic']} | {'unanswerable' if c['unanswerable'] else 'answerable'} | accepted={result['accepted']}", flush=True)
# Gate decisions are a post-hoc function of the cached outputs; recompute with the current verify.
v1_stored = sum(r['accepted'] for r in records)
for r in records:
    r['accepted'] = verify(r['baseline'], r['quote'], r['evidence'])
    r['gated'] = r['baseline'] if r['accepted'] else ''
# Entailment gate (book ch. 46): one extra judge call per case, cached like the generations.
ent_path = ROOT / 'results/entailment.jsonl'
ent = {}
if ent_path.exists():
    ent = {json.loads(l)['id']: json.loads(l) for l in ent_path.read_text().splitlines()}
for i, r in enumerate(records):
    if r['id'] in ent:
        continue
    start = time.perf_counter()
    supported, raw = claim_supports(r['question'], r['baseline'], r['quote'])
    ent[r['id']] = {'id': r['id'], 'supported': supported, 'raw': raw, 'seconds': time.perf_counter() - start}
    with ent_path.open('a', encoding='utf-8') as handle:
        handle.write(json.dumps(ent[r['id']]) + '\n')
    print(f"entail {i+1:02d}/24 | supported={supported}", flush=True)
for r in records:
    r['entailed'] = r['baseline'] if ent[r['id']]['supported'] else ''
methods = {'always_refuse': lambda r: '', 'baseline': lambda r: r['baseline'],
           'gated': lambda r: r['gated'], 'entail_gated': lambda r: r['entailed']}
n_ans = sum(not r['unanswerable'] for r in records); n_un = sum(r['unanswerable'] for r in records)
summary = {'n': len(records), 'answerable': n_ans, 'unanswerable': n_un, 'methods': {}}
em_by = {}
for name, fn in methods.items():
    preds = [fn(r) for r in records]
    em = [max(float(normalize(p) == normalize(g)) for g in (r['answers'] or [''])) for p, r in zip(preds, records)]
    fs = [max(f1(p, g) for g in (r['answers'] or [''])) for p, r in zip(preds, records)]
    em_by[name] = em
    summary['methods'][name] = {
        'exact_match': sum(em) / len(em), 'exact_match_count': int(sum(em)), 'exact_match_wilson95': wilson(int(sum(em)), len(em)),
        'token_f1': sum(fs) / len(fs),
        'answerable_em': int(sum(e for e, r in zip(em, records) if not r['unanswerable'])),
        'unanswerable_em': int(sum(e for e, r in zip(em, records) if r['unanswerable'])),
        'unsupported_answers': sum(bool(p.strip()) and r['unanswerable'] for p, r in zip(preds, records)),
        'answerable_refusals': sum(not p.strip() and not r['unanswerable'] for p, r in zip(preds, records)),
        'answered': sum(bool(p.strip()) for p, r in zip(preds, records))}
# Citation precision (book ch. 38): quotes that contain a gold answer / all non-empty quotes.
quotes = [r for r in records if isinstance(r['quote'], str) and r['quote'].strip()]
supporting = [r for r in quotes if any(normalize(g) and normalize(g) in normalize(r['quote']) for g in r['answers'])]
summary['citation_precision'] = {'supporting_quotes': len(supporting), 'quotes': len(quotes),
    'value': len(supporting) / len(quotes) if quotes else None,
    'definition': 'quote contains a gold answer span (normalized) / all non-empty quotes; unanswerable questions have no gold, so any quote there is decorative'}
# Paired comparison of the EM rows against the ungated baseline.
summary['paired_vs_baseline'] = {}
for name in ('gated', 'entail_gated', 'always_refuse'):
    b = sum(1 for x, y in zip(em_by['baseline'], em_by[name]) if x and not y)
    c = sum(1 for x, y in zip(em_by['baseline'], em_by[name]) if y and not x)
    summary['paired_vs_baseline'][name] = {'baseline_only_correct': b, f'{name}_only_correct': c, 'mcnemar_exact_p': round(mcnemar_exact(b, c), 4)}
summary['gate_v1_case_sensitive'] = {'accepted': v1_stored, 'accepted_after_case_fold': sum(r['accepted'] for r in records),
    'note': 'v1 gate used case-sensitive containment while this scorer lowercases; decisions differing between the two are listed in results/audit.json'}
summary['latency_seconds'] = {'median': float(np.median([r['seconds'] for r in records])),
                             'p95': float(np.percentile([r['seconds'] for r in records], 95)),
                             'entail_median': float(np.median([ent[r['id']]['seconds'] for r in records]))}
summary['line_count'] = len((ROOT / 'rag.py').read_text().splitlines())
assert summary['line_count'] <= 50
summary['validation'] = 'PASS: unit checks, labels/spans, complete 24-case run, <=50 lines'
summary['environment'] = {'python': platform.python_version(), 'numpy': np.__version__,
                          'models': 'nomic-embed-text:latest / qwen2.5-coder:3b (digests in results/model_versions.json)'}
summary['frozen_core_sha256'] = hashlib.sha256((ROOT / 'rag.py').read_bytes()).hexdigest()
(ROOT / 'results/summary.json').write_text(json.dumps(summary, indent=2), encoding='utf-8')
print(json.dumps(summary, indent=2), flush=True)
